In [2]:
import pandas as pd

In [3]:
file_path = "question_papers.csv"

In [4]:
df = pd.read_csv(file_path)

In [5]:
df.head()

,Title,Advertisement No,Date,Download Link
0,"Accounts Officer, Class-2, Gujarat Accounts Se...",6/2026-27,30-06-2026 06:04 PM,https://gpsc.gujarat.gov.in/Documents/Advertis...
1,"Accounts Officer, Class-1, Gujarat Accounts Se...",4/2026-27,30-06-2026 06:03 PM,https://gpsc.gujarat.gov.in/Documents/Advertis...
2,"Assistant Professor, Politics in Government Ar...",94/2025-26,29-06-2026 12:52 PM,https://gpsc.gujarat.gov.in/Documents/Advertis...
3,"Assistant Professor, Sociology in Government A...",91/2025-26,29-06-2026 12:52 PM,https://gpsc.gujarat.gov.in/Documents/Advertis...
4,"Assistant Professor, Computer Science in Gover...",85/2025-26,29-06-2026 12:51 PM,https://gpsc.gujarat.gov.in/Documents/Advertis...

In [6]:
df.shape

(1057, 4)

In [8]:
# year wise group by Date Column
df['Date'] = pd.to_datetime(df['Date'])

df['Year'] = df['Date'].dt.year
df_yearly = df.groupby('Year').size().reset_index(name='Count')
df_yearly

   Year  Count
0  2017     46
1  2018    115
2  2019     89
3  2020     58
4  2021    236
5  2022     30
6  2023     53
7  2024     64
8  2025    208
9  2026    158